apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejauniv-rampup
spec:
  selector: 
    matchLabels: 
      app: springboot-k8s-mysql
  replicas: 1  # a quantidade de pods que vou criar
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers: # definir container
        - name: ejauniv-rampup # nome de container
          image: ejauniv-rampup # qual a imagem que quero rodar (posso por a versao na frente se quiser)
          imagePullPolicy: IfNotPresent # por default puxa do docker hub. Com essa config procura local e se nao achar puxa do hub.
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username
            - name: DB_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
---

apiVersion: v1 
kind: Service 
metadata: 
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.


